CREATE TABLE owners (
	id SERIAL PRIMARY KEY,
	first_name VARCHAR(64) NOT NULL,
	last_name VARCHAR(64) NOT NULL,
	middle_name VARCHAR(64) NOT NULL,
	phone_number VARCHAR(64) NOT NULL
)

CREATE TABLE cars (
	id SERIAL PRIMARY KEY,
	car_number VARCHAR(20) NOT NULL,
	brand VARCHAR(30) NOT NULL,
	id_owner INTEGER REFERENCES owners(id)
)

CREATE TABLE spots (
	id SERIAL PRIMARY KEY,
	spot_number INTEGER NOT NULL,
	is_available BOOLEAN NOT NULL
)

CREATE TABLE bookings (
	id SERIAL PRIMARY KEY,
	id_car INTEGER REFERENCES cars(id) NOT NULL,
	id_spot INTEGER REFERENCES spot(id) NOT NULL,
	start_date TIMESTAMP NOT NULL,
	end_date TIMESTAMP NOT NULL,
	is_paid BOOLEAN NOT NULL,
	is_active BOOLEAN NOT NULL
)
